#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 29 14:40:59 2024

@author: lenenortje
"""

"""Storing data in Python
1. Lists
2. Dictionaries
3. Data Frames - spesific to pandas 
"""

import pandas

file = pandas.read_csv("country_data.csv")

print(file)

"""
 Age Gender       Country
0    39      M  South Africa
1    25      M      Botswana
2    29      F  South Africa
3    46      M  South Africa
4    22      F         Kenya
5    35      F    Mozambique
6    22      F       Lesotho
7    49      M         Kenya
8    30      M         Kenya
9    40      F         Egypt
10   30      M         Sudan
"""

age1 = 30
age2 = 25
age3 = 29

#[ ] defines a list 
age =[30,25,29,46,22]

print(age)
"""
[30, 25, 29, 46, 22]
"""
print(age[0])
#30
#due to indexing, because start counting at zero. 

print(age[1])

print(min(age))
#22

print(max(age))
#46

print(sum(age))
#152

print(len(age))
#5

print(sum(age)/len(age))
#30.4

g1 = "M"
g2 = "F"
g3 = "F"

gender = ["M","F","F"]

c1= "South Africa"
c2 = "Lesotho"

country_list = ["Sout Africa", "Lesotho" ]

print(age[0:2])
#[30, 25]

print(age[0:3])
#[30, 25, 29]

age.append(100)

print(age)
#[30, 25, 29, 46, 22, 100]

age.insert(0,75)
#first number the location, second number the value to be added,insert 

print(age)
#[75, 30, 25, 29, 46, 22, 100]

"""
Dictionaries 
- collection of key:value pairs 
- they are un-ordered 
- curly brackets 

"""

mammals = {"cat":"a cute animal", "lion":"king of the jungle", "elephant":"a gigantic herbivore"}

print(mammals["cat"])

"""
Data Frames
"""

fruits = ["apple", "banana", "orange", "grape", "kiwi"]

size_nm = [9.8, 10.1, 13.2, 8.7, 20.5]

fruit_sizes = {
    'fruits': fruits, 
    'sizes': size_nm
    
    }

"""
df - dataframe
"""

df = pandas. DataFrame(fruit_sizes)

print(df['fruits'])

print(df['sizes'])

print(df['fruits'].min())

print(df['sizes'].max())

print(df.describe())

print(df[df["sizes"] > 10])

print(df[1:3])

prices = [10.00, 12.50, 16.00, 23.00, 7.00]

df['prices']= prices 

df.drop(columns=["sizes"], inplace=True)

print(df)





